### ISSUE TITLE
Issue with stock app icon

### ISSUE THREAD

**Issue by ZedNait** [kitsunyan/foxy-droid#15]
Stock app icon color flashes between gray and blue when app is downloading.
![output](https://user-images.githubusercontent.com/13302457/86376240-c33f2380-bc97-11ea-8d08-a71fd7d0f749.gif)

**Comment by kitsunyan** [comment]
Actually, blinking is a server issue: I expect icon to present on the server (since it's declared in metadata), but it returns 404 instead. So every time the header is updated, icon blinks.

This is partially solved by https://github.com/kitsunyan/foxy-droid/commit/0d4aedad87dee1c9d3b872aac7d305314d49e295, so the icon won't blink every time progress bar is updated. But some actions will require full header update, and this will lead to blinks sometimes. But I don't think it's necessary to fix that.
