### ISSUE TITLE
new features for Foxy Droid 

### ISSUE THREAD

**Issue by srfirouzi** [kitsunyan/foxy-droid#18]
Hello
Foxy Droid is cool,but by add features can is better than this

- new and updated app list (I founded your app in f-droid latest)
- new config options 
  - set Time of update app list
  - can set auto download update app

Tanks for Foxy Droid

**Comment by kitsunyan** [comment]
> new and updated app list (I founded your app in f-droid latest)

It's already done in 1.1 (which is not released to F-Droid yet, and it might take some more time)

> set Time of update app list

I don't understand what is it.

> can set auto download update app

I don't think it's a good idea. As I mentioned multiple times, cache cleaner is very aggressive, if you don't update day or two, all downloaded packages will be deleted.

**Comment by kzwg63tf** [comment]
also it would be cool if you added:
  * `share` button
  * support for repository link (pressed in link and auto suggest to add this repo in foxy)

**Comment by kitsunyan** [comment]
Unfortunately, there is no so much place in the toolbar to display a new button, since I intentionally wanted to not add items into overflow menu. It should also be possible to use file manager for sharing (at least Foxy Droid displays the package name, so it shouldn't be hard to find the APK in /data).

Regarding repository links, I'll probably add this feature, though there may be some problems since it's not that easy to detect such links sometimes. It's still possible to just copy the link, and when you click "add repository" the URL field (and even fingerprint field) will be filled automatically.

**Comment by kzwg63tf** [comment]
share button is for application link for examle if I want to share such cool application as https://f-droid.org/app/nya.kitsunyan.foxydroid

and I can’t copy the display name, even if it would be possible it’s not convenient to manually add there https://f-droid.org/app/

i think it can be done, for example, after a long press on the displayed name this name or link will be copied in clipboard

**Comment by kitsunyan** [comment]
> share button is for application link for examle if I want to share such cool application as https://f-droid.org/app/nya.kitsunyan.foxydroid

Well, it's not possible. There are a lot of repositories, and only F-Droid repository has a website. It should world like that.

> i think it can be done, for example, after a long press on the displayed name this name or link will be copied in clipboard

It won't be intuitive that this text is clickable.

**Comment by srfirouzi** [comment]
> set Time of update app list
on f-droid can set time for update automaticly
f-droid > settings > automatic update interval 
and this options  (never/ every 2week/weekly/daily/.... )

**Comment by kitsunyan** [comment]
> set Time of update app list
> on f-droid can set time for update automaticly
> f-droid > settings > automatic update interval
> and this options (never/ every 2week/weekly/daily/.... )

I don't see any reasons to make it configurable. I mean, at all. It doesn't consume your mobile traffic (because you can set to sync over Wi-Fi only), it doesn't place notifications every time it syncs (because there are `If-None-Match` and `If-Modified-Since` checks). If you don't want to see notifications, you can disable them. Moreover, there are a lot of pitfall when you set long update intervals (more than a few days), for instance they can reset on phone reboot (because these intervals are not exact like when you set alarm time in your clock application, so they aren't tracked anyhow, this will also overcomplicate things a lot). Updating every 12 hours is pretty optimal, and I'm pretty sure it's optimal for any cases.

**Comment by kitsunyan** [comment]
"Update all" feature issue is moved here https://github.com/kitsunyan/foxy-droid/issues/42 because it's more specific about it.
