### ISSUE TITLE
foxy droid doesn't respect system animation settings

### ISSUE THREAD

**Issue by lvmm** [kitsunyan/foxy-droid#21]
All animations are turned off in system-developer options-xxxxx animation scale, and yet transitions between tabs are still animated. Please respect system animation settings or make a configuration option to turn animations off. 1.1

**Comment by kitsunyan** [comment]
There is no such thing as "system animation settings". There are _developer_ options which allow to change animation speed, which is useful for _developers_ to test their animations (e.g. test how they look when they slow).

These settings **can't be respected** by design, since they're private settings used by appropriate system components targeted by these settings (Window Manager is targeted by "window animation scale" and "transition animation scale" settings, Animator framework is targeted by "animator duration scale", etc). I mean, these aren't "user settings" and can't be used directly to adjust scrolling speed.

I also don't want to add a new option in application settings:

1. I don't like adding settings for each behavior, because it's impossible to satisfy everyone, and it's unfair to satisfy one group of people and don't satisfy other group of people.
2. There it just no way to adjust the slide speed of this component in a sane way (without forking and rewriting it, ofc, which I'm not planning to do, and I doubt it's "sane" to do).

This component is named `ViewPager2` from Android Jetpack. You can probably try to leave a ticket on their issue tracker about this behavior.

**Comment by kitsunyan** [comment]
Hmm, actually I'm not quite right about "can't be respected". There are some specific cases when they actually can. For instance, it's possible to detect that Animator's animations are disabled using https://developer.android.com/reference/android/animation/ValueAnimator#areAnimatorsEnabled(), but it requires Android 8 and higher. I don't want to use reflection for this to support older Android versions, tbh.

**Comment by kitsunyan** [comment]
Forget :<
It was actually pretty easy to change https://github.com/kitsunyan/foxy-droid/commit/2c4f693d64b4867c68117931a54f8229a546050d
