### ISSUE TITLE
Warn when a vulnerability is found

### ISSUE THREAD

**Issue by andinus** [kitsunyan/foxy-droid#26]
F-Droid app shows a warning in updates tab whenever a vulnerability is found. 

![F-Droid app warning](https://ttm.sh/Q8o.jpg)

**Comment by kitsunyan** [comment]
This just displays the applications with "KnownVuln" anti-features if installed. I don't want to add this: neither I want to add a special treatment of this specific anti-feature, not I want to overcomplicate things to add its support (and this will be not that easy to do, especially because this anti-feature may be per-package anti-feature, not only per-application).

**Comment by andinus** [comment]
I see. Sorry, I don't think I understand.

Won't a simple rule to check if the application has this anti-feature work? Like at the same time when checking if an update is available, this thing could be checked for.

**Comment by kitsunyan** [comment]
> Won't a simple rule to check if the application has this anti-feature work?

This will require reworking database schema, and actually will require a lot of reworking, especially if I need to add per-package anti-feature check. The list of applications screens and specific application screen work differently.
