### ISSUE TITLE
RFE: Full text search

### ISSUE THREAD

**Issue by t184256** [kitsunyan/foxy-droid#27]
Full text search isn't working, at least in 1.1. This is the biggest blocker for me.

**Comment by kitsunyan** [comment]
What does "full text search" mean? For now it searches across `package_name`, `name`, and `summary` fields. Do you want include `description`? The problem is that searching in description may yield many irrelevant results, like you're trying to search for github client, but instead you get a lot of applications like "hentai manga reader" because it includes github link in the description.

Another possible solution is ranking the search results by matched fields, e.g. results with matches in `package_name`, `name`, or `summary` are above those with `description` matches only.

**Comment by t184256** [comment]
Yes, you got it right, and, yes, appending them after the rest makes sense. I doubt that separating the other results makes much sense though.

**Comment by blackva** [comment]
Would be nice to have this feature. Many applications don't have proper summary and generic queries such as "browser", "adblock", "terminal", etc. sometimes don't have what you want. It also helps to improve discoverability of apps. I would suggest ranking applications the way you, @kitsunyan , proposed, but also add sorting by update date in each rank, so the most up-to-date application are always on top. 

It is a bit irrelevant, but I would also suggest not to show any search results until user types 2 or 3 characters.

**Comment by kitsunyan** [comment]
> but also add sorting by update date in each rank, so the most up-to-date application are always on top.

The same sorting order configuration is used both in regular and search modes.



> It is a bit irrelevant, but I would also suggest not to show any search results until user types 2 or 3 characters.

Doesn't make sense to me.

**Comment by kitsunyan** [comment]
Done https://github.com/kitsunyan/foxy-droid/commit/6467b23c653880d5845395d8b34fb09564c61f3c

**Comment by blackva** [comment]
Thank you! I meant when users make search queries they dont need to see results for 1 or 2 characters because they are very broad. It is unlikely that user will see wanted apps on the top.

**Comment by kitsunyan** [comment]
Sure, they're very broad in the most cases. But there are no technical reasons to introduce such restrictions: if user is satisfied with the result after typing only 2 symbols, let it be so. I don't want to add restrictions out of nowhere.
