### ISSUE TITLE
Add pull down to refresh gesture to sync repos

### ISSUE THREAD

**Issue by Pentaphon** [kitsunyan/foxy-droid#30]
As the title says. Makes syncing easier on taller phones. Set a hard limit so pulling down can only be done every X minutes.

**Comment by kitsunyan** [comment]
> Makes syncing easier on taller phones

Which is not necessary. Pull to refresh pattern is usable if you're going to do that every N minutes or so. In the worst case you'll sync repositories once you start the application.

Also, this duplicates the function of the separate toolbar button, which is even worse.

> Set a hard limit so pulling down can only be done every X minutes.

Why this limit is even needed? This complicate even more.

**Comment by Pentaphon** [comment]
> Which is not necessary. Pull to refresh pattern is usable if you're going to do that every N minutes or so. In the worst case you'll sync repositories once you start the application.
> 
> Also, this duplicates the function of the separate toolbar button, which is even worse.

It's not necessary but it is useful. It saves the user time over having to tap the sync button which is all the way up at the top of the phone and that helps users with tall 20:9 phones. In the case of the "available" tab, you have to press the 3 dot button to drop down the sync button. 

> Why this limit is even needed? This complicate even more.

To keep users from putting a heavy load on the server. I would like to do a manual refresh quickly by swiping whenever I feel like it rather than wait for the app to do it but not let me overdo it.

**Comment by kitsunyan** [comment]
> It's not necessary but it is useful

Actually, it isn't either. Pull-to-refresh pattern is used to update the data on the screen. This process takes 1-3 seconds, or so, depending on the application which uses this pattern. But that's not the case for F-Droid. In fact, when you press the "sync" button, it downloads **a lot** of data which is **not trivial** to process and then store it to the database. And this is repeated for all repositories. Knowing that F-Droid server is slow sometimes, this process can take up to 1 minute, or even longer. This is where pull-to-refresh pattern fails.

I find it extremely annoying to see this feature in the official F-Droid client, which I sometimes triggered accidentally so then I have to wait about a minute until it finishes. Foxy Droid processes repositories much faster, but still it's far from expected 1-3 seconds.

So I think pull-to-refresh is anti-pattern here, and shouldn't exist in Foxy Droid (especially in form of co-existing with a separate toolbar button, it's just a duplication of functions).

> To keep users from putting a heavy load on the server

I don't think I should restrict user's freedom with such nasty things like internal timer which doesn't allow something just because I can think that syncing shouldn't be done very often.

**Comment by Pentaphon** [comment]
Fair enough. It's your project. I'll close this.

**Comment by kitsunyan** [comment]
> In the case of the "available" tab, you have to press the 3 dot button to drop down the sync button.

Actually, it displays "sync" button on first tab if screen DPI is low. I increased the threshold in https://github.com/kitsunyan/foxy-droid/commit/175448dc8df7a76bd247fb78f550a32bf087c0bd, so the button should be visible on more phones by default.

**Comment by Pentaphon** [comment]
> Actually, it displays "sync" button on first tab if screen DPI is low (width >= 480dp). I increased the threshold in [175448d](https://github.com/kitsunyan/foxy-droid/commit/175448dc8df7a76bd247fb78f550a32bf087c0bd) (now width should only be >= 400dp), so the button should be visible on more phones with default DPI configuration.

Thanks, that helps.

**Comment by Pentaphon** [comment]
> Actually, it displays "sync" button on first tab if screen DPI is low (width >= 480dp). I increased the threshold in [175448d](https://github.com/kitsunyan/foxy-droid/commit/175448dc8df7a76bd247fb78f550a32bf087c0bd) (now width should only be >= 400dp), so the button should be visible on more phones with default DPI configuration.

Just installed 1.3 from F-Droid and the sync button doesn't show in the available tab on a 720x1280 phone. (Moto G3)

![foxy](https://user-images.githubusercontent.com/49374058/90247398-5452ff80-ddeb-11ea-95f9-cd133893d73f.jpg)

**Comment by kitsunyan** [comment]
That's normal, because most 5'' (+- 0.5'') phones have 360dp screen width, which is actually sad, because for any screen higher than 4.6'' everything becomes too big (360dp width corresponds to x2 scale for 720x1280 screen, or x3 scale for 1080x1920).

You can try to decrease your dpi setting. By default your phone has 320 dpi (x2 scale), if you decrease it to 288 dpi (x1.8 scale) or lower, your screen width will become >= 400dp and the button will appear.

**Comment by Pentaphon** [comment]
> That's normal, because most 5'' (+- 0.5'') phones have 360dp screen width, which is actually sad, because for any screen higher than 4.6'' everything becomes too big (360dp width corresponds to x2 scale for 720x1280 screen, or x3 scale for 1080x1920).
> 
> You can try to decrease your dpi setting. By default your phone has 320 dpi (x2 scale), if you decrease it to 288 dpi (x1.8 scale) or lower, your screen width will become >= 400dp and the button will appear.

Ah, never mind then. I'll just deal with it.
