### ISSUE TITLE
About scroll, swipe

### ISSUE THREAD

**Issue by GreenJunkie** [kitsunyan/foxy-droid#37]
It's a great app.  When I swipe my screen vertically to scroll, the tabs may switch or the list may not scroll.  Maybe I should be careful, but it wasn't comfortable.

**Comment by kitsunyan** [comment]
I use AndroidX components to build horizontal pages and vertical lists. You should probably be familiar with this behavior since this is how it's implemented in about 95% other applications with vertical lists inside horizontal tabs. You should probably be more careful, or you may experience some hardware touchscreen issues.

**Comment by GreenJunkie** [comment]
Thanks for the quick answer. It was a problem with my device. I'll be careful.

**Comment by linsui** [comment]
Hi, I have the same issue. In other apps (e.g. Firefox) when I swipe from top right to bottom left, if the angle is larger than 45 deg the screen will scroll vertically. However, in FoxyDroid sometimes the screen will scroll horizontal even when the angle is larger than 60 deg.

**Comment by xlucn** [comment]
I have similar experience, especially at either end of the scrolling list. The scroll is triggered with an angle much closer to vertical than some other apps (maybe they are not using AndroidX?). Is there any options to control some related threshold in the AndroidX components?
