### ISSUE TITLE
More repositories

### ISSUE THREAD

**Issue by GhilbiGithubilbi** [kitsunyan/foxy-droid#5]
Hello!

Foxy Droid is a wonderful piece of code, thank you for it.

I have noticed that Foxy Droid provides only a few repositories, like F-Droid and Guardian Project.

It would be an excellent idea to add few popular repositories to the base, but unchecked by default. Repositories like:

MicroG: https://microg.org/fdroid/repo?fingerprint=9BD06727E62796C0130EB6DAB39B73157451582CBD138E86C468ACC395D14165

IzzyOnDroid: https://apt.izzysoft.de/fdroid/repo?fingerprint=3BF0D6ABFEAE2F401707B6D966BE743BF0EEE49C2561B9BA39073711F628937A

Bromite: https://fdroid.bromite.org/fdroid/repo?fingerprint=E1EE5CD076D7B0DC84CB2B45FB78B86DF2EB39A3B6C56BA3DC292A5E0C3B9504

Bitwarden: https://mobileapp.bitwarden.com/fdroid/repo?fingerprint=BC54EA6FD1CD5175BCCCC47C561C5726E1C3ED7E686B6DB4B18BAC843A3EFE6C

That would be a real QoL change. Thank you!

**Comment by kitsunyan** [comment]
I added repositories which are included to the official F-Droid client by default. It's not a good idea for me to decide which repositories to include, it's just not fair. You should always be able to add any repository you wish, especially since you can simply copy the address to a clipboard and repository form will be filled automatically.
